Williamhe/1357976 add python run build command
microsoft/Oryx pull request #1108
Opened 2021-09-17 07:26 UTC by william-msft

- [ ] The purpose of this PR is explained in this message or in an issue. If an issue please include a reference as \#\<issue\_number\>.
- [ ] Tests are included and/or updated for code changes.
- [ ] Proper license headers are included in each file.

2021-09-28 16:32 UTC, arroyc requested changes
rebase to main and then rerun validation build .. because you are using flask  app which broke our pipeline after the dependencies got updated. we want to make sure this test is running fine before we merge them to main

2021-09-28 16:32 UTC, arroyc commented on src/BuildScriptGenerator/Python/PythonPlatform.cs
> +                _logger.LogWarning("RUN_BUILD_COMMAND environment variable detected");
nit: logdebug  would be better IMO

2021-09-29 17:20 UTC, william-msft commented on src/BuildScriptGenerator/Python/PythonPlatform.cs
> +                _logger.LogWarning("RUN_BUILD_COMMAND environment variable detected");
Agree, updated

2021-11-18 21:39 UTC, cormacpayne requested changes

2021-11-18 21:39 UTC, cormacpayne commented on doc/configuration.md
> +RUN_BUILD_COMMAND            | Custom command ran at the very end. After virtual envionment, `pip install`, creating python package egg, enabling collecstatic, compresing virtual environment (where a
What's the difference between this `RUN_BUILD_COMMAND` and the `POST_BUILD_COMMAND`? Just from reading the descriptions they seem similar, but it's hard to tell the difference.

2021-11-18 21:39 UTC, cormacpayne commented on src/BuildScriptGenerator/Python/PythonBashBuildSnippet.sh.tpl
> +	echo 'Running $RUN_BUILD_COMMAND'
nit: just to make the log a little more clear, I would suggest changing the wording here to:

`echo 'Running the following provided RUN_BUILD_COMMAND: $RUN_BUILD_COMMAND`

2021-11-18 21:39 UTC, cormacpayne commented on src/BuildScriptGenerator/Python/PythonPlatform.cs
> +            string runBuildCommand = Environment.GetEnvironmentVariable("RUN_BUILD_COMMAND");
nit: I'd suggest pulling the `"RUN_BUILD_COMMAND"` string out into its own private `const` defined at the top of this file.

2022-04-29 20:04 UTC, william-msft commented
Closing until we re-visit

2022-04-29 20:04 UTC, closed without merging